//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCv.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TblEducation
    {
        public int ID { get; set; }
        [Required(ErrorMessage ="Bu alaný boþ geçemezsiniz.")]
        public string Heading { get; set; }
        [Required(ErrorMessage ="Bu alaný boþ geçemezsiniz.")]
        public string subtitle1 { get; set; }
        [Required(ErrorMessage ="Bu alaný boþ geçemezsiniz.")]
        public string subtitle2 { get; set; }
        [StringLength(10, ErrorMessage ="Lütfen en fazla 10 karakterlik veri giriþi yapýn")]
        public string GNO { get; set; }
        [Required(ErrorMessage ="Bu alaný boþ geçemezsiniz.")]
        public string Date { get; set; }
    }
}
